apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
   - name: my-container
     image: nginx:latest
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: slave1
            operator: In
            values:
              - sri

