---
apiVersion: v1
kind: Pod
metadata:
 name: postgres-pod
 labels:
  author: sri
  type: database
spec:
 containers:
  - name: databaser
    image: postgres
    env:
      - name: POSTGRES_PASSWORD
        value: myuser
      - name: POSTGRES_USER
        value: myuser
      - name: POSTGRES_DB
        value: mydb     
...
