---
apiVersion: v1
kind: Pod
metadata:
  name: myjenkins
  labels:
    type: ci-cd
    author: sri
spec:
 containers:
  - name: jenkins
    image: jenkins/jenkins
    ports:
      - containerPort: 8080
        hostPort: 8888 


...  
