---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
  labels:
    type: webserver
    author: srikanth
spec:
  replicas: 3
  template:
    metadata:
      name: httpd-pod
      labels:
        type: webserver
    spec:
      containers:
       - name: httpd
         image: httpd
         ports:
          - containerPort: 80
            hostPort: 8888   
