---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    author: sri
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30004
  selector:
    type: webserver
...    
