---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis-deployment
  labels:
    type: redis-db
    author: msr

spec:
  replicas: 1
  selector:
    matchLabels:
      type: redis-db
  template:
    metadata:
      name: redis-app-pod
      labels:
        type: redis-db
    spec:
      containers:
        - name: redis 
          image: redis
             
