---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: result-deployment
  labels:
    name: result-app
    author: msr

spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app
    spec:
      containers:
        - name: resultapp
          image: dockersamples/examplevotingapp_result      
