---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    author: msr
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30005
  
  selector:
    name: result-app    
