---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: worker-deployment
  labels:
    name: worker-app
    author: msr

spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app
    spec:
      containers:
        - name: workerapp
          image: dockersamples/examplevotingapp_worker     
